appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
provider: {linux_aarch64: default, linux_ppc64le: default}
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mP/QZ62Ey+PxGf2Z7Ebb21ZnbzdVuFWidP+ZYbo6p9chOBfr4i/MyCgF5yFtLWg9w02AagD9H0VTinpMdEowu68hCjVV8MAMVIZS3/TYL0UJXZyTz6S4DB0ZSh9thNzrZG1saUK03BAv2jxqWjp26uhY6z7xiC73R4S9gO7mEIt23wRSq+c7F+2b2OSfltwbvi+9FksZcp9m/bwOihZs5aiHv4aiNxANYGhw5kuVPs5Ed0K0tfvLOEI8iSh5oWO9g40JSq+6Xk+73LA8IhKX1l5RYIDnnCQk0RPt+8yTp2v78Wk0t5VihJfAoblbxYv3ew5Z6c20z2Dtstn4RdJavgS5ZO5aD6OiNwR0TKxn6RL/02TURHyPznVyIFOyi0t3eHcAfBGHc5JjKqc8H5Vwj9PetVVIzC401YqHJje7bXLgP4ldOPcL18CcBAoL0fCbXLozF2JOSY6Bi/aayTxARdxkiWRJGneXNhejwzjQiCfRnuMvtQ9/+SacBg3fS235FzmxgqLLZ5Bm2tamUauYvWfLJCtcReZWGxZiH9XR1NIUqDrdnm6WDZW1eE9ZBU15LPYxKI0P7w3tvpf73c7Uzjqk7bTpnYy3KYk2dhLSxf629k/mlxHgx/PjtQogIrRUvZ1bpao5vDPRRJRgEaTcEEIowUx2m0qqoq7crN4XrxU=}
